### ISSUE TITLE
Implement SDD update on welcome call data

### ISSUE THREAD

**Issue by bjendres** [CiviCooP/be.aivl.streetimport#15]
1. compare with recorded SEPA mandate (based on reference)  => if not there (shouldn't happen) -> create
2. if changes 
   //     => adjust mandate if possible
   //     => end old, create new mandate otherwise
3. if cancellation => end asap.
4. if mandate doesn't exist => FLAG

**Comment by bjendres** [comment]
I added the basic structure, but I'll wait for Iljas answers before implementing the actual mandate modifications.

**Comment by ErikHommel** [comment]
@systopia did you get all required answers from Ilja's mail?

**Comment by bjendres** [comment]
Yes, I think so. I'll let you know when more questions come up.

**Comment by bjendres** [comment]
implemented - but needs more testing. Different ticket?
