### ISSUE TITLE
Cater for both comma and semicolon as csv field delimiters

### ISSUE THREAD

**Issue by ErikHommel** [CiviCooP/be.aivl.streetimport#25]
Current settings is default delimiter = semicolon. In some cases comma's might come in. Should we do anything with this?

**Comment by bjendres** [comment]
I don't know. I see two other options:
1. Put it in config
2. Put it in that default mapping, e.g. with a `__delimiter` key. And then add the path to the default mapping as config option.

**Comment by ErikHommel** [comment]
Created a function before, will check

Erik Hommel - CiviCooP (Sent from my phone)

-------- Oorspronkelijk bericht --------
Onderwerp: Re: [be.aivl.streetimport] Cater for both comma and semicolon as csv field delimiters (#25)
Van: SYSTOPIA
Aan: "CiviCooP/be.aivl.streetimport"
Cc: Erik Hommel | CiviCooP

I don't know. I see two other options:
1.  Put it in config
2.  Put it in that default mapping, e.g. with a __delimiter key. And then add the path to the default mapping as config option.
