### ISSUE TITLE
Error campaign_id can not be found with existing campaign

### ISSUE THREAD

**Issue by ErikHommel** [CiviCooP/be.aivl.streetimport#26]
I get an error 'can not find campaign_id '2'' while I have a campaign with id 2 in the database? It is in the SDD mandate, perhaps you already fixed :-)

**Comment by bjendres** [comment]
I'll have look now.

**Comment by bjendres** [comment]
I couldn't reproduce it, it should be working fine. 

@ErikHommel If this still happens, could you send me more information?

**Comment by bjendres** [comment]
Sorry, my bad. There was a bug after all :)

@ErikHommel : please try again an close if fixed

**Comment by ErikHommel** [comment]
Fixed!
