### ISSUE TITLE
BIC should be looked up, is not in import files

### ISSUE THREAD

**Issue by ErikHommel** [CiviCooP/be.aivl.streetimport#31]
Preferably we should look up the BIC. @systopia are there any issues with this?

**Comment by bjendres** [comment]
No, except that the "Little BIC Extension" would have to be installed. 

@ErikHommel : Would we need more than the currently available countries? (Belgium, Netherlands, Austria, Germany, Luxemburg)? Then we would have to add a parser (1-2hrs of work).

**Comment by ErikHommel** [comment]
@systopia I guess not but I will ask Ilja to be sure :-)

**Comment by ErikHommel** [comment]
@systopia Little Bic extension is already installed on AIVL test server.

**Comment by bjendres** [comment]
Regarding the parsers, Ilja wrote:

> Maybe France in addition...

Let me know if/when I should do this...

**Comment by ErikHommel** [comment]
Not yet, should get answer tomorrow.

**Comment by bjendres** [comment]
This should work now
