### ISSUE TITLE
Bank account to be created for contact if not exists

### ISSUE THREAD

**Issue by ErikHommel** [CiviCooP/be.aivl.streetimport#32]
If a new donor is created (or bank account does not exist for an existing one), a bank account should also be created for the donor at the time of street recruitment import. It would automatically be generated at the time of the first SDD action, but preferably bank account is in contact as soon as we know it, which is at import moment.

**Comment by bjendres** [comment]
No problem.

**Comment by bjendres** [comment]
This should work now

**Comment by bjendres** [comment]
> It would automatically be generated at the time of the first SDD action

Just for the record: it would be created when CiviBanking processes (books) the incoming money transaction.
