### ISSUE TITLE
Add check if CiviSepa is installed

### ISSUE THREAD

**Issue by ErikHommel** [CiviCooP/be.aivl.streetimport#35]

**Comment by bjendres** [comment]
...Both are needed in the current workflow - although we could continue w/o CiviBanking - that's just for the accounts (https://github.com/CiviCooP/be.aivl.streetimport/issues/32)

**Comment by ErikHommel** [comment]
@systopia will include check for both in install and enable

**Comment by ErikHommel** [comment]
Will also include Little Bic extension
