### ISSUE TITLE
Settings page logic flawed

### ISSUE THREAD

**Issue by bjendres** [CiviCooP/be.aivl.streetimport#37]
Just an observation: The settings page `civicrm/admin/setting/aivl_import_settings` requires the employees handling stuff to be set. But if the "Relationship types for other/employee" setting at the bottom isn't correct, there might be no contacts to select from. In turn, you cannot change this setting, because the form validation doesn't let you save any changes => deadlock :)

**Comment by ErikHommel** [comment]
Yes, I did raise issue #36 about this too :-) I am solving it for now by initially selecting all relationship types as 'Employee'
