### ISSUE TITLE
Preferred language after import

### ISSUE THREAD

**Issue by Iljadecoster** [CiviCooP/be.aivl.streetimport#40]
Now set to English. Should be Dutch as default.

(Not that key important, we don't use that actively in AIVL. But...)

**Comment by ErikHommel** [comment]
@Iljadecoster I do not know what you mean exactly? You mean the preferred language of the contact/donor that is being imported?

**Comment by Iljadecoster** [comment]
It should looks urgly. There is no prefered language setting in the csv. We don't use it. We asume they speak Dutch...

But when a new contact is created with the import it appears to set the language to English.

Anyway, not the main issue...

**Comment by ErikHommel** [comment]
@Iljadecoster CiviCRM defaults the contact preferred language to the default language of the installation. In the AIVL test environment this is set to English:
![aivl print language](https://cloud.githubusercontent.com/assets/458090/8545252/fa4f6598-24ac-11e5-9361-d4b26c97e397.png)

If you change this setting to Dutch, the default preferred language should also automatically be set to Dutch for new imports. Let me know if this happens, then I can close the issue.

**Comment by Iljadecoster** [comment]
OK.

We'll check this in our civi. Anyway. Not a priority.

Ilja

---

Ilja De Coster
Medewerker Fondsenwerving en Relatiebeheer
                                   -----------------------------------------------------------------------|
 Amnesty International Vlaanderen                                                                         |
 vzw                                                                                                      |
 Kerkstraat 156 - B-2060 Antwerpen                                                                        |
                                                                                                          |
 T +32 3 270 34 30                                                                                        |
 M +32 4 96 17 16 19                                                                                      |
 F +32 3 235 78 12                                                                                        |
 W www.aivl.be                                                                                            |
                                   -----------------------------------------------------------------------|

Volg ons:

This email and any files transmitted with it are confidential and intended
solely for the use of the individual or entity to whom they are addressed.
If you have received this email in error please notify the system manager.

**Comment by Iljadecoster** [comment]
OK. I see this now. Don't fix indeed.
