### ISSUE TITLE
Activities: info on recruitement

### ISSUE THREAD

**Issue by Iljadecoster** [CiviCooP/be.aivl.streetimport#41]
Frequency_unit is not filled in from the csv import

**Comment by ErikHommel** [comment]
@Iljadecoster can you give me an example? I see the data in the print and in the database?:

![aivl print issue 41](https://cloud.githubusercontent.com/assets/458090/8545313/7c1cc87c-24ad-11e5-8a97-621617079d7f.png)

**Comment by Iljadecoster** [comment]
Frequency-unit is indeed filled inin the SDD-mandate info under the contributions.

But it is missing under the activities where a picture is kept of the orginial recruitement data:
![printscreen004](https://cloud.githubusercontent.com/assets/12933926/8570586/b863eaac-2581-11e5-97bc-d2343bf67a4a.png)
