### ISSUE TITLE
SSD made?

### ISSUE THREAD

**Issue by Iljadecoster** [CiviCooP/be.aivl.streetimport#43]
I don't see any SDD made in a contact record.

I guess this is because the SDD module is not yet installed in the test amnestycivi.be?

**Comment by ErikHommel** [comment]
@Iljadecoster Can you attach a screen print please? I do see a SDD ...
![aivl issue 43](https://cloud.githubusercontent.com/assets/458090/8507662/609ce43c-224c-11e5-87b7-74e50c9c77a7.png)

**Comment by Iljadecoster** [comment]
Ok. I see it now. I looked at the wrong place. You can close this item.

---

Ilja De Coster
Medewerker Fondsenwerving en Relatiebeheer
                                   -----------------------------------------------------------------------|
 Amnesty International Vlaanderen                                                                         |
 vzw                                                                                                      |
 Kerkstraat 156 - B-2060 Antwerpen                                                                        |
                                                                                                          |
 T +32 3 270 34 30                                                                                        |
 M +32 4 96 17 16 19                                                                                      |
 F +32 3 235 78 12                                                                                        |
 W www.aivl.be                                                                                            |
                                   -----------------------------------------------------------------------|

Volg ons:

This email and any files transmitted with it are confidential and intended
solely for the use of the individual or entity to whom they are addressed.
If you have received this email in error please notify the system manager.
