### ISSUE TITLE
Scheduled job takes only 1 csv

### ISSUE THREAD

**Issue by Iljadecoster** [CiviCooP/be.aivl.streetimport#44]
If 2 csv are put in the load map, and the execute now of the scheduled job is run. Street import takes only the first file.
Only after a second 'execute now', he takes the second csv

**Comment by ErikHommel** [comment]
@systopia I would expect the scheduled job to run all files in the folder, is that correct?

**Comment by Iljadecoster** [comment]
Indeed it should run all the files in the folder.

**Comment by bjendres** [comment]
One question: if there is an abort event in one file, should the rest of the files still be processed?

**Comment by ErikHommel** [comment]
I think it makes sense if it does, it could well be that the next file is fine and we want to get all data in the system as soon as we can. Agree @Iljadecoster ?

**Comment by Iljadecoster** [comment]
Indeed as Erik says: all data should be asap in the system.An issue in one data set should not cause delay in processing the next data set.But of course (in log file?) we meed to keep track of files that are not processed wel to resolve the issue.MvgIlja--Ilja De CosterAmnesty International Vlaanderen

---

Ilja De Coster
Medewerker Fondsenwerving en Relatiebeheer

Amnesty International Vlaanderen vzw
  
Kerkstraat 156 - B-2060 Antwerpen  
   
T +32 3 270 34 30
M +32 4 96 17 16 19
F +32 3 235 78 12
W www.aivl.be

Volg ons:  
   
 

This email and any files
transmitted with it are confidential and intended solely for the use of
the individual or entity to whom they are addressed. If you have received
this email in error please notify the system manager.
Erik Hommel --- Re: [be.aivl.streetimport] Scheduled job takes only 1 csv (#44) --- Van:"Erik Hommel" notifications@github.comAan:"CiviCooP/be.aivl.streetimport" be.aivl.streetimport@noreply.github.comCc:"Iljadecoster" iljad@aivl.beDatum:vr, 3-jul.-2015 09:50Onderwerp:Re: [be.aivl.streetimport] Scheduled job takes only 1 csv (#44)I think it makes sense if it does, it could well be that the next file is fine and we want to get all data in the system as soon as we can. Agree @Iljadecoster ?

**Comment by bjendres** [comment]
...but the file would still be moved to the archive folder, right? Otherwise it would just be picket up in the next cycle.
Alternatively, we could move it to a "failed" location, but then Erik would have to provide this path by an extra setting.

**Comment by ErikHommel** [comment]
I think failed location is a good idea

Erik Hommel - CiviCooP (Sent from my phone)

-------- Oorspronkelijk bericht --------
Onderwerp: Re: [be.aivl.streetimport] Scheduled job takes only 1 csv (#44)
Van: SYSTOPIA
Aan: "CiviCooP/be.aivl.streetimport"
Cc: Erik Hommel | CiviCooP

...but the file would still be moved to the archive folder, right? Otherwise it would just be picket up in the next cycle.
Alternatively, we could move it to a "failed" location, but then Erik would have to provide this path by an extra setting.

**Comment by Iljadecoster** [comment]
Might be a failed folder would be easier to deal with afterwards. I didn't think of it because, but I might prefer this.If not at least in the log file we would need the name of the failed file so we can easily find it in the processed folder.Both ways might work - look at what is the best (easiest?) to implement.Ilja--Ilja De CosterAmnesty International Vlaanderen

---

Ilja De Coster
Medewerker Fondsenwerving en Relatiebeheer

Amnesty International Vlaanderen vzw
  
Kerkstraat 156 - B-2060 Antwerpen  
   
T +32 3 270 34 30
M +32 4 96 17 16 19
F +32 3 235 78 12
W www.aivl.be

Volg ons:  
   
 

This email and any files
transmitted with it are confidential and intended solely for the use of
the individual or entity to whom they are addressed. If you have received
this email in error please notify the system manager.
SYSTOPIA --- Re: [be.aivl.streetimport] Scheduled job takes only 1 csv (#44) --- Van:"SYSTOPIA" notifications@github.comAan:"CiviCooP/be.aivl.streetimport" be.aivl.streetimport@noreply.github.comCc:"Iljadecoster" iljad@aivl.beDatum:vr, 3-jul.-2015 12:25Onderwerp:Re: [be.aivl.streetimport] Scheduled job takes only 1 csv (#44)...but the file would still be moved to the archive folder, right? Otherwise it would just be picket up in the next cycle.
Alternatively, we could move it to a "failed" location, but then Erik would have to provide this path by an extra setting.

**Comment by ErikHommel** [comment]
I will add a fail location to the settings @systopia $config->getFailFileLocation

**Comment by bjendres** [comment]
I implemented a marginally tested version, but I have the following remarks:
- you seem to have changed the input format. @ErikHommel: could you check in a new `sample.csv`, or provide me with one by email?
- @ErikHommel: Could you implement the `Config:getFailFileLocation()` method?
- I suggest we also extend the logging facilities - right now the log doesn't state what file the messages came from, which wasn't a problem when we only processed one file at a time. What do you guys think?

**Comment by ErikHommel** [comment]
@systopia implemented `phpConfig:getFailFileLocation()` and checked in new samples file.

**Comment by bjendres** [comment]
Seems to work just fine now.

@ErikHommel : What about fixing / improving the logging? Could be up to 1 hr of work...

**Comment by ErikHommel** [comment]
@systopia makes sense,and I can see more coming after the test on the subject of error logging. But it would be nice to at least remove the notices before then :-) You want to take that on?

**Comment by Iljadecoster** [comment]
Works. You can close this.

**Comment by Iljadecoster** [comment]
I would put a better logging on an issue list for second release.

**Comment by bjendres** [comment]
Ok, good.
