### ISSUE TITLE
Activities: campaign id

### ISSUE THREAD

**Issue by Iljadecoster** [CiviCooP/be.aivl.streetimport#46]
It seems the campaign_id from the csv is not been added into the created activity streetrecruitement.

**Comment by ErikHommel** [comment]
@Iljadecoster can you attach screen print, line of error etc?

**Comment by Iljadecoster** [comment]
The field for campaign in the activity record is empty:

![printscreen003](https://cloud.githubusercontent.com/assets/12933926/8509161/a3cb9e28-2293-11e5-8c31-be5acf9adc13.png)

**Comment by bjendres** [comment]
Ok, I'll start adding the campaign to _all_ activities...

**Comment by bjendres** [comment]
@ErikHommel: Please test again

**Comment by ErikHommel** [comment]
@Iljadecoster I will put a new release on your test environment tomorrow morning and send you a list of the issues that should be fixed. Can you then retest please?

**Comment by Iljadecoster** [comment]
Ok, I'll be testing tomorow afternoon.If possible, do remove the impoted test data as well, not to be confused...(don't remove other stuff in our test civi - do day I was adding custum fields to campaigns...)Ilja--Ilja De CosterAmnesty International Vlaanderen

---

Ilja De Coster
Medewerker Fondsenwerving en Relatiebeheer

Amnesty International Vlaanderen vzw
  
Kerkstraat 156 - B-2060 Antwerpen  
   
T +32 3 270 34 30
M +32 4 96 17 16 19
F +32 3 235 78 12
W www.aivl.be

Volg ons:  
   
 

This email and any files
transmitted with it are confidential and intended solely for the use of
the individual or entity to whom they are addressed. If you have received
this email in error please notify the system manager.
Erik Hommel --- Re: [be.aivl.streetimport] Activities: campaign id (#46) --- Van:"Erik Hommel" notifications@github.comAan:"CiviCooP/be.aivl.streetimport" be.aivl.streetimport@noreply.github.comCc:"Iljadecoster" iljad@aivl.beDatum:di, 7-jul.-2015 18:49Onderwerp:Re: [be.aivl.streetimport] Activities: campaign id (#46)@Iljadecoster I will put a new release on your test environment tomorrow morning and send you a list of the issues that should be fixed. Can you then retest please?

**Comment by ErikHommel** [comment]
@Iljadecoster you can do that yourself? Delete mandates and then permanently delete contacts?

**Comment by Iljadecoster** [comment]
I'll try ;-)--Ilja De CosterAmnesty International Vlaanderen

---

Ilja De Coster
Medewerker Fondsenwerving en Relatiebeheer

Amnesty International Vlaanderen vzw
  
Kerkstraat 156 - B-2060 Antwerpen  
   
T +32 3 270 34 30
M +32 4 96 17 16 19
F +32 3 235 78 12
W www.aivl.be

Volg ons:  
   
 

This email and any files
transmitted with it are confidential and intended solely for the use of
the individual or entity to whom they are addressed. If you have received
this email in error please notify the system manager.
Erik Hommel --- Re: [be.aivl.streetimport] Activities: campaign id (#46) --- Van:"Erik Hommel" notifications@github.comAan:"CiviCooP/be.aivl.streetimport" be.aivl.streetimport@noreply.github.comCc:"Iljadecoster" iljad@aivl.beDatum:di, 7-jul.-2015 19:34Onderwerp:Re: [be.aivl.streetimport] Activities: campaign id (#46)@Iljadecoster you can do that yourself? Delete mandates and then permanently delete contacts?
