### ISSUE TITLE
Activity location

### ISSUE THREAD

**Issue by Iljadecoster** [CiviCooP/be.aivl.streetimport#47]
In the civi activities their is a field forseen 'location'
Would it make sence to put the Wervinglocatie there...?

**Comment by ErikHommel** [comment]
@Iljadecoster could do, should not be a problem. Do you want me to make that change?

**Comment by Iljadecoster** [comment]
I don't see it as a key issue, but I though it would be better to use as much as possible standard civi-field and as less as possible custom field.

But you know civi better... I leave it to you what you see to be the best way to do.

**Comment by ErikHommel** [comment]
Only if we are sure it has the same functionality, and in this case it has. So I think it makes sense.

Verstuurd vanaf mijn iPad

Op 8 jul. 2015 om 19:47 heeft Iljadecoster <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:

I don't see it as a key issue, but I though it would be better to use as much as possible standard civi-field and as less as possible custom field.

But you know civi better... I leave it to you what you see to be the best way to do.
