### ISSUE TITLE
Membership sign up

### ISSUE THREAD

**Issue by Iljadecoster** [CiviCooP/be.aivl.streetimport#48]
The membership sign up is done fine.

But in the activities:
Why is added by Ilja De Coster, while the street recruitement is added by the name of the recruiter.
The membership should as well be added by the recruiter, I  think.

**Comment by ErikHommel** [comment]
This activity is automatically generated by core CiviCRM, I can not influence this with the API as far as I know. Workaround is to update the activity once the membership is created. I will post a question on StackExchange and implement the workaround if no quick answer.
