### ISSUE TITLE
Membership made twice

### ISSUE THREAD

**Issue by Iljadecoster** [CiviCooP/be.aivl.streetimport#49]
When a welcome call (loading type 2) is created as an activity), then the membership is created a second time - it was already created when the activity streetrecruited was made.

When importing the membership, it should only update what was created already (stop the membership if previously it was created and at welcome call cancelled, or created if it was set to N at streetrecruitement.)

![printscreen001](https://cloud.githubusercontent.com/assets/12933926/8479623/49fd436c-20d9-11e5-811b-4eb0cbf0c76e.png)

**Comment by bjendres** [comment]
Unfortunately the membership extracts only three parameters from the CSV:
- `contact_id`
- `membership_type_id`
- `membership_source`

With these, we would be unable to tell whether this is an existing or new membership. I would suggest the following:

> In WelcomeCall mode, we will create a membership _only_ if there exists no active membership of the same `contact_id` and `membership_type_id`.

If you don't like this, we would have to find a way to uniquely identify the membership.

@ErikHommel: Your thoughts?

**Comment by ErikHommel** [comment]
@systopia For the specific AIVL case, we are adding the life long free membership. So with the combination of membership_type_id and contact_id we should have enough to see if in this specific AIVL case the membership is already there. Generically speaking it is not enough. So you suggestion should work for AIVL.

**Comment by Iljadecoster** [comment]
The following suggestion from Bjorn would work for me, for the AIVL case now:
**
In WelcomeCall mode, we will create a membership only if there exists no active membership of the same contact_id and membership_type_id.
**
