### ISSUE TITLE
New SDD-mandate: offset days for start not calculated

### ISSUE THREAD

**Issue by Iljadecoster** [CiviCooP/be.aivl.streetimport#53]
The start date for SDD-mandates is not set correctly. The offset days form the AIVL-import settings should be added

Should be:
Start Date  Import date + offset days (not yet correct)
Created Date    Import date (now already correct)

![printscreen005](https://cloud.githubusercontent.com/assets/12933926/8570697/74006ede-2582-11e5-9622-88ac22ec67e2.png)

**Comment by bjendres** [comment]
Yes, that's definitely true, sorry. I don't currently even use `getOffsetDays()`.

@ErikHommel: shall I go ahead and fix this? Along with https://github.com/CiviCooP/be.aivl.streetimport/issues/54, https://github.com/CiviCooP/be.aivl.streetimport/issues/56 and https://github.com/CiviCooP/be.aivl.streetimport/issues/57 ?

**Comment by Iljadecoster** [comment]
If this is a budget question: I would say yes ;-)

For this part of the fundraising support we are still within budget. For
other issues we'll might have a budget issue for now (we'll have the budget
meeting tomorrow Erik and Katrin, and you know I'll fight for my budgets)

Anyway the issues on SDD I added to day are key to the whole streetimport
functionality. Without this the whole module wouldn't make sense at all.

---

Ilja De Coster
Medewerker Fondsenwerving en Relatiebeheer
                                   -----------------------------------------------------------------------|
 Amnesty International Vlaanderen                                                                         |
 vzw                                                                                                      |
 Kerkstraat 156 - B-2060 Antwerpen                                                                        |
                                                                                                          |
 T +32 3 270 34 30                                                                                        |
 M +32 4 96 17 16 19                                                                                      |
 F +32 3 235 78 12                                                                                        |
 W www.aivl.be                                                                                            |
                                   -----------------------------------------------------------------------|

Volg ons:

This email and any files transmitted with it are confidential and intended
solely for the use of the individual or entity to whom they are addressed.
If you have received this email in error please notify the system manager.

**Comment by ErikHommel** [comment]
@systopia yes please!

**Comment by bjendres** [comment]
I'm assuming that (Import date + offset days) is more like an "earliest start date", i.e. if the donor has specified a start date in the far future, the offset would not be added to that start date.

BTW:  I'm currently not using the "Import date" from the file, but the time of execution. Is that ok?

@ErikHommel: Please go ahead and test it.

**Comment by Iljadecoster** [comment]
Indeed, you assume right. It is the earliest possible start date.

If the start date the donor indicated (as in the import csv) is the far future, then that indicated start date should be the SDD-start date. Of ever, is the start date indicated by the donor is earlier then importdate+offsetdays, then still importdate+offsetdays should be the SDD start date.

This basically because the offset days are the legal minimum between sign up and first collection.

**Comment by bjendres** [comment]
Great, that's how it's implemented now.
