### ISSUE TITLE
Github labels and clossing issues

### ISSUE THREAD

**Issue by Iljadecoster** [CiviCooP/be.aivl.streetimport#55]
Hey guys,

I can't add labels to issues or close them in github. Any idea why?
I was willing to close some items...

**Comment by Iljadecoster** [comment]
I have found closing, but not the labels ;-)

**Comment by ErikHommel** [comment]
on the right hand side you should see a labels list if you click on 'labels'?
![ilja](https://cloud.githubusercontent.com/assets/458090/8573881/273bc4ce-2594-11e5-89ad-1fee7544b6b5.png)

**Comment by Iljadecoster** [comment]
Yes, I can see the labels. But I can't add or change them.

**Comment by ErikHommel** [comment]
Makes sense, you are not a contributor to the repository.

Verstuurd vanaf mijn iPad

Op 8 jul. 2015 om 19:43 heeft Iljadecoster <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:

Yes, I can see the labels. But I can't add or change them.

**Comment by Iljadecoster** [comment]
OK. So I leave it to you to add labels such as priority, question,...
