### ISSUE TITLE
SDD-mandate: Frequency_interval and cycle day

### ISSUE THREAD

**Issue by Iljadecoster** [CiviCooP/be.aivl.streetimport#56]
As I see it now the Frequency_interval form the import file is not correctly matched to the cycle day in the SDD-part.

The Frequency_interval in the import csv refers to the cycle day for the monthly collections of the SDD.

Frequency-interval 1 = collection in the first half of the month = cycle day 7th of the month
Frequency-interval 2 = collection in the second half of the month = cycle day 21st of the month

Followin example person, has indicated to prefere Frequency interval 1 (correctly imported in the activities)
![printscreen007](https://cloud.githubusercontent.com/assets/12933926/8571827/250a9e2e-2589-11e5-9fcb-71f22ed3a844.png)

BUT, this person has an newly created mandate with cycle date 1 and a startdate in the first half of the month.
![printscreen008](https://cloud.githubusercontent.com/assets/12933926/8571814/1507443c-2589-11e5-91b6-c59234640838.png)

**Comment by Iljadecoster** [comment]
In addition (same screenprint) the Frequency_unit and Frequency_interval from the csv seem not to be integrated correctly:

Frequency_unit: Monthly, annually... -> in SDDmodule this is the field 'Frequency'
(now default mainly monthly, but later this can change)

Frequency_interval: refers to when in the collection month the collection should be done. In the SDDModule this is the field 'Cycle Day'

**Comment by bjendres** [comment]
> The Frequency_interval in the import csv refers to the cycle day for the monthly collections of the SDD.
> Frequency-interval 1 = collection in the first half of the month = cycle day 7th of the month
> Frequency-interval 2 = collection in the second half of the month = cycle day 21st of the month

Ok, I understand where my confusion was. You see, in CiviCRM `frequency_interval` is a fixed term for, well, the interval. A value of '3' along with a `frequency_unit` of 'month' would denominate a quarterly cycle. In this aspect, the field name "Frequency_interval" in the CSV file is poorly chosen :)

I'll fix it, so it'll go into the cycle day. And I'll just assume the CiviCRM `frequency_interval` to be '1' unless otherwise specified by the unit parser.

**Comment by bjendres** [comment]
This should work now, although I currently hardcoded the two cycle days. I see two options here:
1. take it from the CiviSEPA Creditor (1=first cycle day, 2=second cycle day, etc...)
2. put it into the config

@ErikHommel: What do you think?

**Comment by Iljadecoster** [comment]
I think this one should be the way to go:
**
1. take it from the CiviSEPA Creditor (1=first cycle day, 2=second cycle day, etc...)
**
