### ISSUE TITLE
SDD-mandates: cancelled should could be canncelled

### ISSUE THREAD

**Issue by Iljadecoster** [CiviCooP/be.aivl.streetimport#57]
If in the import file a mandate is cancelled (field Cancellation), then it should be cancelled in the SDD-mandates

This person has a cancelled mandate (correct in the activities)
![printscreen009](https://cloud.githubusercontent.com/assets/12933926/8572356/73b6ce0a-258c-11e5-9942-5b41925bced3.png)

BUT: his mandate is still pending. It should be cancelled.
![printscreen010](https://cloud.githubusercontent.com/assets/12933926/8572412/c53eb01c-258c-11e5-89c2-c240b700f92e.png)

(This example the cancellation is already done in the loading type 1. Usually it is in the loading type 2)

**Comment by bjendres** [comment]
@ErikHommel: Please test again.

**Comment by bjendres** [comment]
Please try again.
