### ISSUE TITLE
Import error activity: clarity

### ISSUE THREAD

**Issue by Iljadecoster** [CiviCooP/be.aivl.streetimport#59]
Something for the second release of streetimport -> in to do in august.

The activity created in case of an import error should contain  clear reference to what record generated an error.
So link the activity (with contact field) with the contact-id of the new donor if possible. add the name of the import csv from where the donor comes, the donor_id of the donor somewhere in the information, a recruitement date... any information to help find easily what record was imported wrong.

Soe screenshots to illustrate the uselessness of the activity record now ;-)

![printscreen011](https://cloud.githubusercontent.com/assets/12933926/8615041/a618b96c-26ef-11e5-8706-5171f2704104.png)

![printscreen012](https://cloud.githubusercontent.com/assets/12933926/8615044/abfa0624-26ef-11e5-857e-055092ba0c05.png)

![printscreen013](https://cloud.githubusercontent.com/assets/12933926/8615048/b080775a-26ef-11e5-81d1-9aa8023ea8f1.png)

**Comment by Iljadecoster** [comment]
To add on this:

This is the import error activities list the admin person to whom the errors are assigned sees in his/her activities:

I would prefer: 

ADDED BY: the streetrecruiter (now the admin person handling the errors)
WITH: the newly created donor (now blank)
ASSIGNED: the admin person handling errors (now already correct)

![printscreen015](https://cloud.githubusercontent.com/assets/12933926/8627728/16f3fde2-274d-11e5-9c82-a2afa2ccc75d.png)

**Comment by Iljadecoster** [comment]
To compare: the activities the staaf member in charge of the follow up calls gets:
This is as I would like it for the import errors as well.

![printscreen017](https://cloud.githubusercontent.com/assets/12933926/8628066/000c5504-2750-11e5-90d7-8c2685d97252.png)

**Comment by ErikHommel** [comment]
To do: change the import activity as Ilja described

**Comment by ErikHommel** [comment]
Postpone: discuss with @ilja after the first 'real' data import. (last week of August)

**Comment by ErikHommel** [comment]
Some suggestions been done for 1.2, discuss at that time.
