### ISSUE TITLE
V2: Content of activity details

### ISSUE THREAD

**Issue by Iljadecoster** [CiviCooP/be.aivl.streetimport#60]
To be considered for 2nd release:

What should be the content of the details field of the activity record. 

![printscreen016](https://cloud.githubusercontent.com/assets/12933926/8627871/5c5e42a6-274e-11e5-84f8-f26fa1c06492.png)

**Comment by ErikHommel** [comment]
Discussed with @Iljadecoster : make details empty as there is enough info in custom group
