### ISSUE TITLE
For v1.1. ignore loading type other than 1 or 2

### ISSUE THREAD

**Issue by Iljadecoster** [CiviCooP/be.aivl.streetimport#78]
Make sure the streetimport ignores the records with an other Loading type value than 1 or 2, but does import the rest of the csv file: so only if a record has LT 1 or LT2 it should be imported.
But the whole file should not be stopped if there are records with an other loading type code.

**Comment by ErikHommel** [comment]
I expect this already works, I will test it first locally.

**Comment by ErikHommel** [comment]
Tested this locally importing one record of loading type 3. Result: record is not processed but logged as : 2015-08-27 09:33:29 WARN [/var/www/aivllokaal/sites/default/files/civicrm/csv_load/erik_test_issue_78.csv:3]: Record importeren mislukt []: Geen handlers gevonden

Alle andere zijn wel geïmporteerd, issue kan daarmee gesloten. Eens @Iljadecoster?
