### ISSUE TITLE
Unable to give provider name by using SMS Api Extension

### ISSUE THREAD

**Issue by sandeepmohanty** [CiviCooP/be.aivl.streetimport#83]
I downloaded SMS Api Extension (v1.3) in civicrm version 4.5.0.
After that i am unable to give Provider name.(As there is no option to give provider name)
Then i went to https://github.com/CiviCooP/org.civicoop.smsapi .... There in commits "fixed provider name fixed section". It showing two changing files which was missing in last released SMS Api version 1.3. 4.So i created CRM/Smsapi/CivirulesAction.mgd.php and CRM/Smsapi/CivirulesAction.php inside org.civicoop.smsapi (which is the extension diretory name)
When i opened --> Settings - SMS Provider --> Still creating of provider name option is not coming.

Please suggest.

Please provide a complete updated zip file of sms api. I saw which file you changed CivirulesAction.php that is missing sms api version 3 downloaded file.

**Comment by ErikHommel** [comment]
Issue does not belong to this repo
